def problem():
	# Problem 2
	# Published on 19 October 2001 at 06:00 pm [Server Time]
	# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	 # By starting with 1 and 2, the first 10 terms will be:

	# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

	fib_list = [1,2,3]



	while fib_list[-1]<4000000:
		fib_list.append(fib_list[-1]+fib_list[-2])

	fib_list.pop()


	return sum([x for x in fib_list if x%2==0])


if __name__ == "__main__":
	# Load_MREPOS()
	problem()
	